name: second-workflow
on: workflow_dispatch
jobs:
  start-it:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done - bye!"
      
    
